- import_tasks: node_exporter.yml
  when: '"node_exporter" in actions'

- import_tasks: redis_exporter.yml
  when: '"redis_exporter" in actions'

- import_tasks: postgres_exporter.yml
  when: '"postgres_exporter" in actions'
